#+title: Daniel’s Emacs Configuration

My personal Emacs Configuration, containing bits of code collected from around
the web.  Have fun with it!

* Structure

The main configuration is available in the usual [[init.el]] file, with additional
functionality distributed over files in the [[site-lisp]] directory.  Some private
data is outsources into a separate submodule named =private=, and is not included
in this repository.  The configuration should work nevertheless, even without
these private files.

The main =init.el= file consists mostly of variable assignments, =use-package=
declarations, and initializing the =package= subsystem.  The main lifting is
done by the =db/run-init= function, which is attached to the =after-init-hook=
in =init.el=.  This way, all necessary local hooks and autoloads are set up by
=init.el=, and the =db/run-init= functions only activates a (minimal?)
configurations needed for every session, including modes, keybindings, hydras,
and global hooks.  It also imports some environment variables and starts the
server when running under windows.  Any additional packages are only loaded when
required.

* Compatibility

This configuration is known to work with Emacs 25.2 (and later) on
Debian GNU/Linux and Windows 10 (sigh).

* License

ⓒ 2017 Daniel Borchmann

This configuration is available under the MIT license, see [[LICENSE]] for details.
